# Generated by Django 2.2.9 on 2021-06-29 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetYear',
        ),
    ]
